# eseb (Elixir's Simple Encoder Binary)

[package]
name = "eseb"
version = "0.1.0"
authors = ["Alex Roper <alex@aroper.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "2.33.0"
crc16 = "0"
base64 = "0"
sodiumoxide = "0.2.5"
build_stamp = "1"

[build-dependencies]
build_stamp = "1"